/*
 * Contacts
 *
 * Simple AddressBook API to manage contacts
 *
 * API version: 1.0
 * Contact: john.doe@mail.schwarz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"github.com/rs/cors"
	"log"
	"net/http"

	sw "github.com/JJDoneAway/addressbook/controllers"
	"github.com/JJDoneAway/addressbook/middleware"
)

func main() {
	log.Printf("Server started")

	middleware.AddDummies()
	router := sw.NewRouter()
	handler := cors.AllowAll().Handler(router)

	log.Fatal(http.ListenAndServe(":8080", handler))
}
