package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/JJDoneAway/addressbook/controllers"
	"github.com/JJDoneAway/addressbook/middleware"
	// docs is generated by Swag CLI, you have to import it.
)

var port = "8080"

// @title           GO Example Addressbook
// @version         1.0
// @description     This is a simple GO application with some basic REST CRUD operations.

// @Accept json
// @Produce json

// @contact.name   Johannes Höhne
// @contact.email  Johannes.Hoehne1@mail.schwarz

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html
func main() {
	fmt.Println("Register front controllers...")
	mux := http.NewServeMux()
	middleware.AddDummies()

	mux.HandleFunc("*", func(w http.ResponseWriter, r *http.Request) {
		log.Println("Hallo")
	})

	middleware.RegisterSwagger(mux)

	middleware.RegisterPrometheus(mux)

	controllers.RegisterControllers(mux)

	muxWrapper := middleware.NewPrometheus(mux)

	// start server
	fmt.Println("Start http server on port", port)
	err := http.ListenAndServe(":"+port, muxWrapper)
	fmt.Print("Waiting for requests...")
	if err != nil {
		fmt.Print(err)
	}
}


